name: "Manuel Fischer"
title: "Makler Fischer"
language: "de"
language_direction: "ltr"
permalink: /:title
url: https://makler-fischer.net
author: "Manuel Fischer"

# Jekyll GitHub Plugins 
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-webp

sass:
    sass_dir: _scss
    style: compressed
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: true

include:
  - .htaccess

exclude:
  - .github*
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .bundle*
  - vendor*

############################################################
# Site configuration for the WebP Generator Plugin
webp:
  enabled: true
  quality: 75
  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/img"]
  # Whether to search in nested directories or not
  nested: true
  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  # File extensions for animated gif files 
  gifs: [".gif"]
  # Set to true to always regenerate existing webp files
  regenerate: true
  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp"
  webp_path: nil
  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []
  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################