name: "Manuel Fischer"
title: "Makler Fischer"
language: "de"
language_direction: "ltr"
permalink: /:title
url: https://makler-fischer.net
author: "Manuel Fischer"

# Jekyll GitHub Plugins 
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-loading-lazy

sass:
    sass_dir: _scss
    style: compressed

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: true

# Exclude these files from your production _site
exclude:
  - .github*
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .bundle*
  - vendor*
